services:
  postgres-test:
    image: postgres:17-alpine
    container_name: pomodoro-psql-test
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pomodoro-psql-test:/var/lib/postgresql/data
    networks:
      - pomodoro-net-test

  redis-test:
    image: redis:7.4-alpine
    container_name: redis-container-test
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - pomodoro-redis-test:/data
    networks:
      - pomodoro-net-test

  rabbitmq-test:
    image: rabbitmq:3-management
    container_name: rabbitmq-container-test
    ports:
      - ${RABBIT_PORT1}:5672
      - ${RABBIT_PORT2}:15672
    networks:
      - pomodoro-net-test

networks:
  pomodoro-net-test:
    driver: bridge

volumes:
  pomodoro-psql-test:
  pomodoro-redis-test: