services:
  postgres:
    image: postgres:17-alpine
    container_name: pomodoro-psql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pomodoro_psql:/var/lib/postgresql/data
    networks:
      - pomodoro-net

  redis:
    image: redis:7.4-alpine
    container_name: redis-container
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - pomodoro-net
    volumes:
      - pomodoro_redis:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - ${RABBIT_PORT}:5672
      - ${RABBIT_MANAGEMENT_PORT}:15672
    networks:
      - pomodoro-net

networks:
  pomodoro-net:
    driver: bridge

volumes:
  pomodoro_psql:
  pomodoro_redis: