services:
  postgres:
    image: postgres:17-alpine
    container_name: pomodoro_psql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5435:5432'
    volumes:
      - pomodoro_psql:/var/lib/postgresql/data
    networks:
      - pomodoro-net

  redis:
    image: redis:7.4-alpine
    container_name: redis-container
    ports:
      - '6378:6379'
    networks:
      - pomodoro-net
    volumes:
      - pomodoro_redis:/data

networks:
  pomodoro-net:
    driver: bridge

volumes:
  pomodoro_psql:
  pomodoro_redis: